# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e86ed486a03b7e08900060410016999830c0366dd08c3b4fc38a07249edd439e1bb7bafe85af692d5d5a836e1b9740659dcb06470fb8947b3a3c0b1aae83d92

test:
  secret_key_base: 20e996007103072f87882f96ec461215ca3bea5e9ba0e051ad0c923aa03dd3392f194dd1dce9ac542c86b03e003a30379608dcbbc2211f5925a3a1377b983bcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
